export const locales = [
  { code: 'en', htmlLang: 'en', prefix: '/', label: 'English' },
  { code: 'zh-CN', htmlLang: 'zh-CN', prefix: '/zh/', label: '简体中文' },
  { code: 'ja', htmlLang: 'ja', prefix: '/jp/', label: '日本語' },
  { code: 'zh-HK', htmlLang: 'zh-Hant-HK', prefix: '/zh-hk/', label: '繁體中文' },
];
export const pageIds = ['home', 'products', 'contact'];
export function pathFor(locale, page) {
  if (!pageIds.includes(page)) throw new Error('Unknown page identity');
  return locale.prefix + (page === 'home' ? '' : `${page}/`);
}
export const copy = {
  en: {
    brand: 'Demo Supply', nav: ['Home', 'Products', 'Inquiry'],
    language: 'Language', demo: 'A fictional business website example. Products and specifications are invented.',
    homeTitle: 'Clear product information for business buyers',
    homeDescription: 'A fictional supplier example with product specifications, downloads and an inquiry draft.',
    homeText: 'Choose a model, review its specification and include that model in an inquiry. Each language has its own reviewed text and equivalent page links.',
    homeSections: ['Compare the information', 'Keep the model context'],
    homeDetails: ['The product table gives units, a sample minimum order and the assumptions behind lead time.', 'The inquiry form carries your selected model. Generating a draft does not send a message.'],
    productsTitle: 'Product specifications', productsDescription: 'Two fictional models with consistent units, model identifiers and ordering notes.',
    columns: ['Model', 'Material', 'Size', 'Minimum order', 'Sample lead time'],
    material: ['Paper', 'Recycled paper'], leadTime: ['10–15 working days', '15–20 working days'],
    productNote: 'Dimensions are millimetres. Lead time starts after specification approval. These values are demonstration data, not a sales offer.',
    download: 'Download model notes', request: 'Prepare an inquiry',
    contactTitle: 'Prepare an inquiry draft', contactDescription: 'A local demonstration form that creates an inquiry draft without sending it.',
    formLabels: ['Your name', 'Email', 'Model', 'Quantity', 'Destination'],
    button: 'Generate draft', result: 'Draft generated locally. Nothing has been sent.',
    footer: 'Maintained as an educational example by ZequnWeb.', site: 'ZequnWeb website', siteUrl: 'https://zequnweb.com/',
    noteHeading: 'Fictional model notes', noteLabels: ['Model', 'Material', 'Dimensions', 'Lead time', 'Data status'],
    unit: 'mm', fictional: 'Fictional demonstration data',
  },
  'zh-CN': {
    brand: '演示供应商', nav: ['首页', '产品', '询盘'],
    language: '语言', demo: '虚构企业网站示例。产品和规格均为演示数据。',
    homeTitle: '让企业采购者看懂产品信息',
    homeDescription: '包含产品规格、资料下载与询盘草稿的虚构供应商网站示例。',
    homeText: '先选择型号，核对规格，再把型号带入询盘。每种语言都有独立审核的内容和对应页面链接。',
    homeSections: ['比较具体信息', '保留型号上下文'],
    homeDetails: ['产品表包含单位、示例起订量及交期的起算条件。', '询盘表单保留所选型号。生成草稿不会发送消息。'],
    productsTitle: '产品规格', productsDescription: '两个虚构型号，使用一致的单位、型号标识及订购说明。',
    columns: ['型号', '材料', '尺寸', '最低订购量', '示例交期'],
    material: ['纸材', '再生纸'], leadTime: ['10–15 个工作日', '15–20 个工作日'],
    productNote: '尺寸单位为毫米。交期从规格确认后开始计算。这些数值仅用于演示，不是销售报价。',
    download: '下载型号说明', request: '整理询盘',
    contactTitle: '整理询盘草稿', contactDescription: '在本地生成草稿的演示表单，不会发送询盘。',
    formLabels: ['姓名', '邮箱', '型号', '数量', '目的地'],
    button: '生成草稿', result: '草稿已在本地生成，尚未发送。',
    footer: '由 ZequnWeb 维护的教学示例。', site: 'ZequnWeb 中文网站', siteUrl: 'https://zequnweb.com/zh/',
    noteHeading: '虚构型号说明', noteLabels: ['型号', '材料', '尺寸', '交期', '数据性质'],
    unit: '毫米', fictional: '虚构演示数据',
  },
  ja: {
    brand: 'デモ商社', nav: ['ホーム', '製品', '問い合わせ'],
    language: '言語', demo: '架空の企業サイトの例です。製品と仕様はデモ用のデータです。',
    homeTitle: '企業の購買担当者に伝わる製品情報',
    homeDescription: '製品仕様、資料ダウンロード、問い合わせ下書きを備えた架空の供給会社の例。',
    homeText: '型番を選び、仕様を確認し、その型番を問い合わせに含めます。各言語に独立した確認済み本文と対応ページへのリンクがあります。',
    homeSections: ['具体的な情報を比較する', '型番の情報を引き継ぐ'],
    homeDetails: ['製品表は単位、最低注文数量の例、納期の起算条件を示します。', 'フォームに選択した型番を保持します。下書きの作成は送信ではありません。'],
    productsTitle: '製品仕様', productsDescription: '単位、型番、注文説明を揃えた二つの架空製品。',
    columns: ['型番', '素材', '寸法', '最低注文数量', '納期の例'],
    material: ['紙', '再生紙'], leadTime: ['10〜15 営業日', '15〜20 営業日'],
    productNote: '寸法はミリメートルです。納期は仕様承認後から数えます。数値はデモ用で、販売の申し出ではありません。',
    download: '型番資料をダウンロード', request: '問い合わせを準備',
    contactTitle: '問い合わせの下書きを作る', contactDescription: '送信せずにローカルで下書きを作るデモフォーム。',
    formLabels: ['お名前', 'メールアドレス', '型番', '数量', '仕向地'],
    button: '下書きを作成', result: 'ローカルで下書きを作成しました。送信していません。',
    footer: 'ZequnWeb が保守する学習用の例です。', site: 'ZequnWeb 日本語サイト', siteUrl: 'https://zequnweb.com/jp/',
    noteHeading: '架空製品の型番資料', noteLabels: ['型番', '素材', '寸法', '納期', 'データの性質'],
    unit: 'ミリメートル', fictional: '架空のデモデータ',
  },
  'zh-HK': {
    brand: '示範供應商', nav: ['首頁', '產品', '查詢'],
    language: '語言', demo: '虛構企業網站示例。產品與規格均為示範資料。',
    homeTitle: '讓企業採購者看懂產品資料',
    homeDescription: '包含產品規格、資料下載與查詢草稿的虛構供應商網站示例。',
    homeText: '先選擇型號，核對規格，再將型號帶入查詢。每種語言都有獨立審核的內容及對應頁面連結。',
    homeSections: ['比較具體資料', '保留型號脈絡'],
    homeDetails: ['產品表包含單位、示例最低訂購量及交期的起算條件。', '查詢表格保留所選型號。產生草稿不會傳送訊息。'],
    productsTitle: '產品規格', productsDescription: '兩個虛構型號，使用一致的單位、型號識別及訂購說明。',
    columns: ['型號', '材料', '尺寸', '最低訂購量', '示例交期'],
    material: ['紙材', '再生紙'], leadTime: ['10–15 個工作天', '15–20 個工作天'],
    productNote: '尺寸單位為毫米。交期由規格確認後開始計算。這些數值只供示範，並非銷售報價。',
    download: '下載型號說明', request: '整理查詢',
    contactTitle: '整理查詢草稿', contactDescription: '在本機產生草稿的示範表格，不會傳送查詢。',
    formLabels: ['姓名', '電郵', '型號', '數量', '目的地'],
    button: '產生草稿', result: '草稿已在本機產生，尚未傳送。',
    footer: '由 ZequnWeb 維護的教學示例。', site: 'ZequnWeb 繁體中文網站', siteUrl: 'https://zequnweb.com/zh-hk/',
    noteHeading: '虛構型號說明', noteLabels: ['型號', '材料', '尺寸', '交期', '資料性質'],
    unit: '毫米', fictional: '虛構示範資料',
  },
};
export const models = [
  { id: 'DEMO-01', dimensions: '100 × 80 × 20', moq: 500 },
  { id: 'DEMO-02', dimensions: '150 × 100 × 30', moq: 1000 },
];
